fix(app.service): move event emission outside of db transaction
augustine-institute/triteia pull request #16
Opened 2023-01-12 20:46 UTC by abourge

2023-01-12 20:48 UTC, jhaltercmu2020 approved these changes

2023-01-13 15:30 UTC, Ken-Michalak approved these changes

2023-01-13 15:47 UTC, Ken-Michalak requested changes
The delete should be the same way.

2023-01-13 17:47 UTC, Ken-Michalak approved these changes

2023-01-13 17:47 UTC, merged